<?php
return array(
	'admin/serfing/([0-9]+)' => 'admin/serfing/$1',
	'admin/serfing' => 'admin/serfing',
	'admin/serfing/new/([0-9]+)' => 'admin/serfingnew/$1',
	'admin/serfing/new' => 'admin/serfingnew',

	'admin/feedback/([0-9]+)' => 'admin/feedback/$1',
	'admin/feedback' => 'admin/feedback',
	'admin/feedback/new' => 'admin/feedbacknew',
	'admin/feedback/new/([0-9]+)' => 'admin/feedbacknew/$1',

	'admin/competition/invest' => 'admin/competitioninvest',
	'admin/competition/referal' => 'admin/competitionreferal',
	'admin/leaders' => 'admin/leaders',
	'admin/lottery' => 'admin/lottery',

	'admin/settings' => 'admin/settings',
	'admin/settings/account' => 'admin/settingsaccount',
	'admin/paysystems' => 'admin/paysystems',
	'admin/plans' => 'admin/plans',
	'admin/serfingplans' => 'admin/serfingplans',

	'admin/users/edit/([0-9]+)' => 'admin/usersedit/$1',
	'admin/users/([0-9a-z]+)/([0-9]+)' => 'admin/users/$1/$2',
	'admin/users/([0-9]+)' => 'admin/users/$1',
	'admin/users/search' => 'admin/userssearch',
	'admin/users' => 'admin/users',

	'admin/payments/([0-9]+)' => 'admin/payments/$1',
	'admin/payments/days' => 'admin/paymentsdays',
	'admin/payments' => 'admin/payments',

	'admin/deposits/([0-9]+)' => 'admin/deposits/$1',
	'admin/deposits/days' => 'admin/depositsdays',
	'admin/deposits' => 'admin/deposits',

	'admin/inserts/([0-9]+)' => 'admin/inserts/$1',
	'admin/inserts/days' => 'admin/insertsdays',
	'admin/inserts' => 'admin/inserts',

	'admin/handlepayments' => 'admin/handlepayments',
	'admin/stats' => 'admin/stats',
	'admin/multy' => 'admin/multy',

    'admin/exit' => 'admin/logout',
    'admin/([0-9a-zA-Z]+)' => 'admin/login/$1',
    'admin' => 'admin/login',

	'handler/ymtocken(.*)' => 'handler/ymtocken/$1',
	'handler/ymtocken' => 'handler/ymtocken',
	'handler/ym' => 'handler/ym',
	'handler/ac' => 'handler/ac',
	'handler/fk' => 'handler/fk',
	'handler/py' => 'handler/py',

	'handler/vk(.*)' => 'handler/vk/$1',
	'handler/vk' => 'handler/vk',

	'ajax/balance' => 'ajax/balance',

    'cron/leaders' => 'cron/leaders',
    'cron/lottery' => 'cron/lottery',

    'cron/fakeInserts' => 'cron/fakeInserts',
    'cron/fakePayments' => 'cron/fakePayments',
    'cron/fakeReg' => 'cron/fakeReg',

	'serfing/add' => 'serfing/add',
	'serfing/gettocken' => 'serfing/gettocken',
	'serfing/endview' => 'serfing/endview',
	'serfing/captcha' => 'serfing/captcha',
	'serfing/frame/([0-9a-zA-Z]{32})' => 'serfing/frame/$1',
	'serfing/([0-9]+)' => 'serfing/view/$1',
	'serfing' => 'serfing/serfing',

	'quests/([0-9]+)' => 'account/quests/$1',
	'quests' => 'account/quests',
	'leaders' => 'account/leaders',
	'lottery' => 'account/lottery',
	'refking' => 'account/refking',
	'calc' => 'account/calculator',
	'bonus' => 'account/bonus',
	'settings' => 'account/settings',
    'partner' => 'account/partnership',
    'promo' => 'account/promo',
	'referals/([0-9]+)' => 'account/referals/$1',
	'referals' => 'account/referals',
	'insertserfing' => 'account/insertserfing',
	'exchange' => 'account/exchange',
	'payment' => 'account/payment',
	'insert' => 'account/insert',
	'taxi' => 'account/park',
	'cabinet' => 'account/cabinet',
    'stats' => 'account/stats',
	'exit' => 'account/logout',

	'recovery/reset/([a-zA-Z0-9]{32})' => 'main/recoveryreset/$1',
	'recovery' => 'main/recovery',
	'signup' => 'main/signup',
	'login' => 'main/login',
	'help' => 'main/contacts',
	'reviews/([0-9]+)' => 'main/feedback/$1',
	'reviews' => 'main/feedback',
	'contests' => 'main/competitions',
	'payouts' => 'main/payouts',
	'terms' => 'main/terms',
	'marketing' => 'main/marketing',
	
	'mailcheck?(.*)' => 'main/mailcheck',
	'fail' => 'main/fail',
	'success?(.*)' => 'main/success',
	'success' => 'main/success',
	'ref/([0-9]+)' => 'main/index/$1',
	'' => 'main/index',
	);